---
- name: "{{ name | title }}'s service unit override directory exists"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ name }}.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: "{{ name | title }}'s credentials are installed"
  ansible.builtin.copy:
    dest: "/opt/nx/secrets/{{ name }}.{{ item | regex_replace('_', '.') }}"
    owner: root
    group: root
    mode: "0600"
    content: |
      {{ credentials[item] }}
  loop: "{{ credentials | list }}"
  become: yes

- name: "{{ name | title }}'s credentials are configured"
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ name }}.service.d/credentials.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Service]
      {% for item in credentials %}
      {% set item = item.replace("_", ".") %}
      LoadCredential={{ item }}:/opt/nx/secrets/{{ name }}.{{ item }}
      {% endfor %}
  become: yes
