---
- name: "{{ name | title }}'s systemd service unit is configured"
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ name }}.service"
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description={{ name | title }}
      Wants=redis.target
      Documentation=https://github.com/gbenson/nx-workers

      [Service]
      Type=simple
      ExecStart=/opt/nx/workers/bin/{{ name }}
      ExecReload=/bin/kill -HUP $MAINPID
      Restart=always

      DynamicUser=yes

      {% if capabilities %}
      AmbientCapabilities={{ capabilities }}    # Grant the capability
      CapabilityBoundingSet={{ capabilities }}  # Don't ever get others
      {% endif %}
      NoNewPrivileges=yes

      ProtectSystem=strict
      ProtectHome=yes
      PrivateTmp=yes
      PrivateDevices=yes
      ProtectKernelLogs=yes
      ProtectKernelTunables=yes
      ProtectControlGroups=yes
      ReadOnlyDirectories=/
      UMask=077

      [Install]
      WantedBy=multi-user.target
  vars:
    capabilities: "{{ worker.capabilities | default(None) }}"
  become: yes

- name: "{{ name | title }} is {{ target_state }}"
  ansible.builtin.systemd:
    name: "{{ name }}"
    enabled: "{{ 'true' if is_enabled else 'false' }}"
    masked: no
    state: "{{ 'started' if is_enabled else 'stopped' }}"
  vars:
    is_enabled: "{{ worker.enabled | default(True) }}"
    target_state: |
      {% if is_enabled %}
      enabled and running
      {% else %}
      disabled and stopped
      {% endif %}
  become: yes
